name: Copy-Data

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Copy-Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.4
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'data-bucket'
          sync_dir_from: /data
          sync_dir_to: /temp-data
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
